### ISSUE TITLE
Presentation Layer image in Chapter 2

### ISSUE THREAD

**Issue by youngroklee-ml** [akgold/do4ds#222]
Maybe the image at `https://github.com/akgold/do4ds/blob/main/chapters/sec1/images/presentation-layer.png` needs changes as below regarding "Job" vs "API"? 
- [Run Batches?] -> [Yes] -> [Job]
- [Run Batches?] -> [No] -> [API]

**Comment by akgold** [comment]
Fixed, thanks!
