### ISSUE TITLE
Inconsistency between Chapter 2 and Chapter 6 labs

### ISSUE THREAD

**Issue by youngroklee-ml** [akgold/do4ds#229]
In Chapter 2 lab, path for pins board is `data/model` which is relative path.
In Chapter 6 lab, on the other hand, path for pins board is `/data/model` which is absolute path.

For consistency, it may be better to change either Chapter 2 to use absolute path or Chapter 6 to use relative path.

**Comment by akgold** [comment]
Fixed, thank you!
