### ISSUE TITLE
Chapter 7 Lab: S3 bucket name

### ISSUE THREAD

**Issue by youngroklee-ml** [akgold/do4ds#230]
I appreciate this amazing book! 

This was my first experience of creating an S3 bucket, and my first attempt to create a bucket with name `do4ds-lab` failed. It took several minutes for me to understand that I cannot use the same bucket name `do4ds-lab` that someone else is already using. For a first timer like me, I think some guiding notes would be helpful, something like "Each reader has to use their own unique bucket name that is not used by others, and it should be applied accordingly throughout the lab exercise."

<img width="777" alt="s3-bucket-name-unique" src="https://github.com/akgold/do4ds/assets/30917347/dfedfeba-fdb3-4c43-adbb-9337afa4d8b4">

**Comment by akgold** [comment]
Thank you @youngroklee-ml -- fixed
