### ISSUE TITLE
chapter 1 comprehension question query

### ISSUE THREAD

**Issue by r-leyshon** [akgold/do4ds#231]
Hey there, great book. I'm currently working through the comprehension questions and labs.

Unless I have misunderstood, chapter 1 environment as code comprehension question 2 states:

> Draw a mental map of the relationships between the seven levels of the reproducibility stack. Pay particular attention to why the higher layers depend on the lower ones.

Though it seems that the levels of the reproducibility stack are not referenced within the chapter content. 

This issue would probably be better off in a GitHub discussion by the way, I don't know if you'd agree? In fact, it would be useful to have a discussion thread for each of the chapters so that people can share their responses to the comprehension questions, queries about the labs etc. That way you could crowd source some exemplar solutions.

**Comment by akgold** [comment]
Great point. I've rephrased to: "There's a table of the layers of the data science environment above. It names six items across three layers. Draw a mental map of the relationships between these six items. Pay particular attention to **why** the higher layers depend on the lower ones."
