### ISSUE TITLE
sentence ends abruptly (missing reference ?)

### ISSUE THREAD

**Issue by mdsumner** [akgold/do4ds#257]
https://github.com/akgold/do4ds/blob/b66dad8b9f476a60381139f968cfb6b09483f944/chapters/sec1/1-1-env-as-code.qmd#L243

This `\index{Git}` isn't rendering properly for me, at least when I look at

https://do4ds.com/chapters/sec1/1-1-env-as-code.html#step-3-collaborate-or-deploy

fwiw to me the sentence reads like

> Sharing a requirements file makes downloads and uploads much more manageable, especially if you’re using .

![image](https://github.com/user-attachments/assets/d5b20b62-a8a1-4a2c-8d4e-a0a014514ca6)

**Comment by akgold** [comment]
Thanks @mdsumner!
