### ISSUE TITLE
Possible typo in 10  Getting a real URL

### ISSUE THREAD

**Issue by SamEdwardes** [akgold/do4ds#5]
Hi Alex - I was using this chapter as reference and saw a potential error. The third row in the table has a different IP address than the first row in the table. I assume that they should be the same?

Potential issue:

https://github.com/akgold/do4ds/blob/4591d6b8ab8cb751e1d16450699b6c8244200f6d/chapters/sec2/using-urls.qmd#L86-L90

Correction:

```md
 | Path/Host | Type  | Target         | 
 |-----------|-------|----------------| 
 | `@`       | A     | `143.122.8.32` | 
 | `www`     | CNAME | example.com    | 
 | `*`       | A     | `143.122.8.32` | 
```

**Comment by akgold** [comment]
Ah! Great catch. I actually did want it to be different, but that needs to be explained.

Fixed in https://github.com/akgold/do4ds/commit/8f3d4d36c30afc7b2aa41f8bc26a95cb089c6e3e
